---
apiVersion: v1
kind: Secret
metadata:
  name: app02-secret
  namespace: web02
  labels:
    org.bstu.student.fullname: "Gorodnichuk_Ilya_Aleksandrovich"
    org.bstu.student.id: "22023"
    org.bstu.group: "AS-576"
    org.bstu.variant: "02"
    org.bstu.course: "RSIOT"
type: Opaque
stringData:
  DUMMY_SECRET: "secret-value-22023"