apiVersion: v1
kind: Namespace
metadata:
  name: state-as-576-22023-v02
  labels:
    org.bstu.student.fullname: "Gorodnichuk.Ilya.Aleksandrovich"
    org.bstu.student.id: "22023"
    org.bstu.group: "AS-576"
    org.bstu.variant: "02"
    org.bstu.course: "RSIOT"