apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    org.bstu.student.fullname: {{ .Values.student.fullName | quote }}
    org.bstu.student.id: {{ .Values.student.id | quote }}
    org.bstu.group: {{ .Values.student.group | quote }}
    org.bstu.variant: {{ .Values.student.variant | quote }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  type: {{ .Values.service.type }}