apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mon-{{ .Release.Name }}
  namespace: monitoring
  labels:
    app: {{ .Release.Name }}
    org.bstu.student.fullname: {{ .Values.student.fullName | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s